spring:
  profiles:
    active:
      - dev
---
server:
  port: 5566
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8882/eureka/,http://localhost:8881/eureka/
---
server:
  port: 6677
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8882/eureka/,http://localhost:8881/eureka/